title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: cccc/jekyll-theme-rtd
#remote_theme: carlosperate/jekyll-theme-rtd
# Theme settings:
site_author: An Nhan
repo_url: "https://github.com/annhan/marlin"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
